### ISSUE TITLE
run_model crashes without defined drifts

### ISSUE THREAD

**Issue by JonathonMSmith** [sami2py/sami2py#129]
**Describe the bug**
When using the run_model function without providing exb drifts, sami2py.x crashes when trying to read the exb.inp file.
This appears to be because exb.inp is not included on fresh install. 

**To Reproduce**
1. follow installation steps
2. follow example steps up to "run_model"

**Expected behavior**
Example should work fine without specifying exb drifts.

**Desktop (please complete the following information):**
 - OS: Debian 18.04.05 LTS
 - Python 3.6
 - conda env

**Comment by JonathonMSmith** [comment]
Should we remove exb.inp from the gitignore or create one and fill it with zeros on install?

**Comment by jklenzing** [comment]
I think we should just initialize a zero-filled file.  Otherwise we run into the ever-changing exb.inp file.

**Comment by jklenzing** [comment]
I was able to verify this on a fresh install.

**Comment by JonathonMSmith** [comment]
> 
> 
> I was able to verify this on a fresh install.

same here.

**Comment by jklenzing** [comment]
Closing with merge of #130
