### ISSUE TITLE
Sami2py failed to run model

### ISSUE THREAD

**Issue by andu2013** [sami2py/sami2py#146]
Calledprocesserror
import sami2py
path= r"F:\PhD 2013\1st year\Sem II\Space\Unit 3 equa torial Iono instability\activity and homework\sami2out"
sami2py.utils.set_archive_dir(path=path)
sami2py.run_model(tag='run_name', lon=0, year=2012, day=210)
CalledProcessError: Command './sami2py.x' returned non-zero exit status 2.

**Screenshots**
![image](https://user-images.githubusercontent.com/76777651/120206690-2e8ccf00-c234-11eb-9066-c0bf927f5600.png)

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [brave]
 - Version [V1.25.68 ]

**Comment by jklenzing** [comment]
Thanks for reaching out.  We've had some patches for better usage on windows, but this looks like an issue we haven't caught.  I've pushed a tentative patch to the code, but it is not yet merged into the main branch.  If you're installing through github, try:
```
git checkout jklenzing-patch-1
```
before running the `python setup.py`

You should be able to run the code from there.  We're planning on finalizing all updates to the main branch in the next few weeks.

**Comment by andu2013** [comment]
Thank you, no calledprocessEerror but it makes the pc busy to get the output. I am using core i7 @ 1.8 GH with 8GB ram. How long should I wait to get the output?
Best

**Comment by jklenzing** [comment]
It should take about 15 minutes or less, assuming you're using the default output steps and run length.  The load routine may take about a minute or so to read all the files and convert to arrays.

**Comment by andu2013** [comment]
Thank you so much!
If possible, please let me get a kind of guiding document to simulate
contour plots of Rayleigh-Taylor instability for different km scale
perturbations.
With many Thanks

Andargie Gerawork

**Comment by jklenzing** [comment]
Right now the example code we have is here:  https://sami2py.readthedocs.io/en/rc0.2.3/sample_workflow.html

You might want to look into the `growin` project, which is building Rayleigh-Taylor Instability growth rates calculations off of sami2py.  https://github.com/JonathonMSmith/growin

Note that sami2py does not have the capability to generate perturbations as ESF seeds.  You would probably need a fully 3D model for this.  But you could look at the expected growth rates in the background to see whether the climate is favorable for bubble generation.

**Comment by andu2013** [comment]
Thanks, I will check it out.
Andargie Gerawork
Lecturer,
Physics Department
Bahir Dar University
Bahir Dar, Ethiopia

**Comment by jklenzing** [comment]
Updates pushed into the rc0.2.3 branch.  Let me know if you run into more trouble.
