### ISSUE TITLE
gfortran in Mac Monterrey

### ISSUE THREAD

**Issue by kokichau** [sami2py/sami2py#171]
Fortran library was not compiled with standard Xtools in Monterrey 12.1 (Mac with Apple M1 chip)

The main errors were

=====
gfortran: warning: couldn’t understand kern.osversion ‘21.6.0
gfortran -fno-range-check -fno-automatic -ffixed-line-length-none -c hwm14.f90
gfortran: warning: couldn’t understand kern.osversion ‘21.6.0
gfortran -fno-range-check -fno-automatic -ffixed-line-length-none -o sami2py.x sami2py-1.00.o grid-1.00.o hwm93.o hwm07e_modified.o  hwm14.o apexcord.o nrlmsise00_modified.o
gfortran: warning: couldn’t understand kern.osversion ‘21.6.0
ld: warning: building for macOS 10.4 is deprecated
ld: warning: Csu support file -lcrt1.o not found, changing to target macOS 10.8 where it is not needed
ld: library not found for -lgcc_s.10.4
collect2: error: ld returned 1 exit status
make: *** [compile] Error 1

=====

The problem was solved by installing gfortran for Monterrey 12.1 from github, i.e.,  
https://github.com/fxcoudert/gfortran-for-macOS/releases

**Comment by jklenzing** [comment]
Thanks for the report! We'll update our instructions accordingly.
