### ISSUE TITLE
netCDF output for data archiving

### ISSUE THREAD

**Issue by jklenzing** [sami2py/sami2py#5]
Include a post-processing routine to archive data output as a netCDF with appropriate metadata.
- [x] to_netcdf method to save data from class -- #116
- [x] include metadata in netcdf file
- [x] export metadata to Dataset.attrs?

**Comment by jklenzing** [comment]
We could use the pysat netcdf output routine to generate the netcdfs.  Likewise, we could add an instrument object in pysat to directly read these for comparison with instruments.  This does increase dependencies, but it might be smoother for future comparisons.

**Comment by scivision** [comment]
A factor for doing the conversion to NetCDF in Python instead of in Fortran is that Windows users would need to have NetCDF development libraries if NetCDF is done in Fortran (unless you distributed the compiled library in a wheel).  netCDF4 is [distributed as a wheel for Windows](https://pypi.org/project/netCDF4/#files) so no problem there (in Python)

**Comment by jklenzing** [comment]
Now that `xarray` is incorporated, a post-process routine to convert to netCDF should be trivial to incorporate.

**Comment by JonathonMSmith** [comment]
Do we want only the .dat files to be in the netCDF file? I could also include the namelist and version information in the netCDF.

**Comment by JonathonMSmith** [comment]
Sorry this is taking a while. At this point I see a couple ways forward. 

Immediately parse the sami output as netCDF and archive only the netCDF.
Copy the sami output to the archive and subsequently parse the model output as netCDF. 

The former will end up changing the testing of the core functions by removing some and adding others. The latter approach will only add new unit tests.

**Comment by jklenzing** [comment]
> Do we want only the .dat files to be in the netCDF file? I could also include the namelist and version information in the netCDF.

The metadata should be included. This should include the name list and other optional inputs like ExB.

**Comment by jklenzing** [comment]
I think the first option is the cleanest way to go. It’s cleaner in the end. 

You could also test using the I formatted vs formatted files to see if there is a significant speed gain. As I recall, the binary files are a lot smaller. 

This is for the next milestone, so no rush here.

**Comment by jklenzing** [comment]
Also, we should get #84 merged in first since this updates a lot of code in this region. Some of that code may be deleted as part of the update here, but it will simplify the merge of branches.

**Comment by jklenzing** [comment]
NOTE TO SELF: The sami2py instrument has been added to the develop version of pysatModels.  When updating the metadata for netCDF here, make sure to include the date so that the ut can be properly conveted to datetime.

Conversely, just output datetime to the dataset.

**Comment by aburrell** [comment]
I would recommend keeping the current time format and adding a date to the top.  Also add units to all your data.  This will make it simple for the pysat instrument to have the uth and index in datetime.  It will also make it easy for non-python users to read the netCDF output.

**Comment by jklenzing** [comment]
- [ ] add metadata to `xr.Dataset.attrs`
- [ ] add units to data values

**Comment by jklenzing** [comment]
Closing with merge of #140.
