### ISSUE TITLE
Tab issue in _core

### ISSUE THREAD

**Issue by JonathonMSmith** [sami2py/sami2py#90]
**Describe the bug**
"No files to move!" message being printed even when files are moved.
This is because the tab spacing for this print statement is wrong.

**To Reproduce**

follow the tutorial

**Expected behavior**
This should only print if files are not moved

**Desktop (please complete the following information):**
 - OS:  Windows 10
 
 - 0.2.0

**Comment by jklenzing** [comment]
Closed with merge of #91.
